name: swig-build-action
description: Build, install, and cache swig from source on apt based systems
inputs:
  version:
    description: "Version of swig to build"
    required: false
    default: 4.0.2
  cache-key:
    description: "Additional cache key component (optional)"
    required: false
runs:
  using: "composite"
  steps:
  - name: swig-apt-deps
    run: sudo apt-get install build-essential libpcre2-dev libpcre3-dev autoconf automake libtool bison git curl -qq -y
    shell: bash
  - name: cache-swig
    if: startsWith(github.ref, 'refs/tags/v') != true
    id: cache-swig
    uses: actions/cache@v4
    with:
      path: swig_build_dir
      key: ${{ runner.os }}-${{ inputs.version }}-swig-${{ inputs.cache-key }}
  - name: build-swig
    if: steps.cache-swig.outputs.cache-hit != 'true'
    run: |
      sudo apt remove '^swig.*' -y -qq || true
      rm -rf swig_build_dir
      mkdir -p swig_build_dir
      cd swig_build_dir
      curl -s -L https://github.com/swig/swig/archive/refs/tags/v${{ inputs.version }}.tar.gz --output swig-src.tar.gz
      tar xf swig-src.tar.gz
      cd swig-${{ inputs.version }}
      ./autogen.sh
      ./configure
      make
      sudo make install
    shell: bash
  - name: install-swig
    if: steps.cache-swig.outputs.cache-hit == 'true'
    working-directory: swig_build_dir/swig-${{ inputs.version }}
    run: |
      sudo apt remove '^swig.*' -qq || true
      sudo make install
    shell: bash