name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ${{ matrix.config.runs_on }}
    container: ${{ matrix.config.container }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-20.04
          runs_on: ubuntu-latest
          container: "ubuntu:focal"
          arch: x64
        - os: ubuntu-22.04
          runs_on: ubuntu-22.04
          container: ""
          arch: x64
        - os: ubuntu-24.04
          runs_on: ubuntu-22.04
          container: ""
          arch: x64
        - os: debian-11
          runs_on: ubuntu-latest
          container: debian:bullseye-slim
          arch: x64
        - os: ubuntu-22.04-arm
          runs_on: ubuntu-22.04-arm
          container: ""
          arch: arm64
        - os: debian-testing
          runs_on: ubuntu-latest
          container: debian:testing-slim
          arch: x64
        - os: debian-unstable
          runs_on: ubuntu-latest
          container: debian:unstable-slim
          arch: x64
    name: test-swig-build-action
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/Utc
    steps:
    - uses: actions/checkout@v5
    - name: apt
      run: |
        apt update
        apt install -y sudo tzdata
    - name: swig build
      uses: ./
      with:
        version: 4.4.1
    - name: swig version
      run: swig -version