name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:bionic
    name: test-swig-build-action
    steps:
    - uses: actions/checkout@v5
    - name: apt
      run: |
        apt update
        apt install -y sudo
    - name: swig build
      uses: ./
      with:
        version: 4.1.1
    - name: swig version
      run: swig -version